source 'https://rubygems.org'

gem 'awesome_print'
gem 'byebug'
gem 'capybara'
gem 'concurrent-ruby'
gem 'engtagger'
gem 'escape_utils'
gem 'hexapdf'
gem 'http'
gem 'nokogiri'
gem 'pry'
gem 'pry-byebug'
gem 'rubocop'
gem 'smarter_csv'
gem 'tty-prompt'
gem 'tty-spinner'
gem 'watir'
